server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centre_dentaire_appointement
    username: root
    password:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: appointment-service
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    org.springframework.security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
