server:
  port: 8082
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patient/**
#          filters:
#            - RewritePath=/api/patient/(?<remaining>.*), /${remaining}
        - id: document-service
          uri: lb://patient-service
          predicates:
            - Path=/api/documents/**
#          filters:
#            - RewritePath=/api/documents/(?<remaining>.*), /${remaining}
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointment/**
#          filters:
#            - RewritePath=/api/appointment/(?<remaining>.*), /${remaining}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka