server:
  port: 8082
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patient/**

        - id: document-service
          uri: lb://patient-service
          predicates:
            - Path=/api/documents/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointment/**

        - id: facture-service
          uri: lb://facture-service
          predicates:
            - Path=/api/facture/**

        - id: ressource-service
          uri: lb://ressource-service
          predicates:
            - Path=/api/ressource/salle/**

        - id: product-service
          uri: lb://ressource-service
          predicates:
            - Path=/api/ressource/product/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka