server:
  port: 8082
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patient/**

        - id: document-service
          uri: lb://patient-service
          predicates:
            - Path=/api/documents/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointment/**

        - id: facture-service
          uri: lb://facture-service
          predicates:
            - Path=/api/facture/**

        - id: salle-service
          uri: lb://ressource-service
          predicates:
            - Path=/api/ressource/salle/**

        - id: ressource-service
          uri: lb://ressource-service
          predicates:
            - Path=/api/ressource/product/**

        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
