server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centre_dentaire_notification
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: notification-service
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    org.springframework.security: DEBUG
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
