server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centre_dentaire_patient
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: patient-service
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    org.springframework.security: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
